[project]
name = "imgdl"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = []

# --------------------------------------------------------------------------
# Dev environment
# --------------------------------------------------------------------------
[dependency-groups]
dev = []
