# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Config",
    "DownloadResult",
    "download_images",
]

@typing.final
class Config:
    r"""
    Download configuration. All fields have sensible defaults.
    """
    @property
    def buffer_size(self) -> builtins.int: ...
    @property
    def connections_per_host(self) -> builtins.int: ...
    @property
    def dns_cache_ttl_secs(self) -> builtins.int: ...
    @property
    def max_concurrent(self) -> builtins.int: ...
    @property
    def max_concurrent_per_host(self) -> builtins.int: ...
    @property
    def max_retries(self) -> builtins.int: ...
    @property
    def retry_base_delay_ms(self) -> builtins.int: ...
    @property
    def connect_timeout_secs(self) -> builtins.float: ...
    @property
    def request_timeout_secs(self) -> builtins.float: ...
    @property
    def batch_timeout_secs(self) -> typing.Optional[builtins.float]: ...
    @property
    def naming_strategy(self) -> builtins.str: ...
    @property
    def write_metadata(self) -> builtins.bool: ...
    @property
    def write_summary(self) -> builtins.bool: ...
    @property
    def runtime_threads(self) -> builtins.int: ...
    def __new__(cls, buffer_size: builtins.int = 524288, connections_per_host: builtins.int = 1, dns_cache_ttl_secs: builtins.int = 300, max_concurrent: builtins.int = 200, max_concurrent_per_host: builtins.int = 100, max_retries: builtins.int = 3, retry_base_delay_ms: builtins.int = 100, connect_timeout_secs: builtins.float = 10.0, request_timeout_secs: builtins.float = 30.0, batch_timeout_secs: typing.Optional[builtins.float] = None, naming_strategy: builtins.str = 'url_based', write_metadata: builtins.bool = False, write_summary: builtins.bool = False, runtime_threads: builtins.int = 0) -> Config: ...

@typing.final
class DownloadResult:
    r"""
    Result of downloading a single URL.
    """
    @property
    def url(self) -> builtins.str: ...
    @property
    def success(self) -> builtins.bool: ...
    @property
    def path(self) -> typing.Optional[builtins.str]: ...
    @property
    def error(self) -> typing.Optional[builtins.str]: ...
    @property
    def size_bytes(self) -> typing.Optional[builtins.int]: ...
    @property
    def elapsed_ms(self) -> typing.Optional[builtins.float]: ...
    @property
    def content_hash(self) -> typing.Optional[builtins.str]: ...
    @property
    def retries_attempted(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...
    def to_dict(self) -> dict[str, typing.Any]: ...

def _download_images_plaintext(urls: typing.Sequence[builtins.str], output_dir: builtins.str = '.', config: typing.Optional[Config] = None) -> builtins.list[DownloadResult]:
    r"""
    Same as `download_images`, but over plain TCP with no TLS negotiation.
    
    **Test-only.** Not re-exported from the `imgdl` package and not covered by
    any stability guarantee.
    
    The production path always negotiates TLS, so an `http://` URL cannot
    succeed through `download_images`. Without this hook, the Python test suite
    could only ever assert on error paths offline — which is why the original
    suite had no successful-download coverage at all. This lets pytest run the
    real orchestrator, pool and output layers against a local HTTP server.
    
    Uses its own process-global downloader, so it cannot disturb the state that
    `download_images` relies on.
    """

def download_images(urls: typing.Sequence[builtins.str], output_dir: builtins.str = '.', config: typing.Optional[Config] = None) -> builtins.list[DownloadResult]:
    r"""
    Download images from URLs to the output directory.
    
    Args:
        urls: List of image URLs to download.
        output_dir: Directory to save downloaded images. Defaults to current directory.
        config: Download configuration. Defaults to Config() with all defaults.
    
    Returns:
        List of DownloadResult objects, one per URL, in input order.
    
    Raises:
        ValueError: If urls is empty.
        OSError: If output directory cannot be created or written to.
    """

